theme: jekyll-theme-cayman
google_analytics:
# show_downloads: true

title: Astor's Redemption
description: >
  Logs of a long-termed, story-changing BoTW modding project.<br>1인 1프로젝트 : 젤다 모딩 개발일지

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
  -
    scope:
      type: posts
    values:
      description: Default post description
